Repository ayansiddiqui007/Hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#6 Added login and registration webpage
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#8 Create game.py #1
  game.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#7 Created a static site to show on browser
  atatic_site.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#12 Create titactoe.py
  titactoe.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#9 Create game1.py
  game1.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#10 Create game3.py
  game3.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#13 Updated readme.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest 2023

#17 .
  atatic_site.html
  game1.py
  game3.py
  style.css
Labels: hacktoberfest, hacktoberfest-accepted
